apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    spec:
      containers:
      - name: staging-container
        image: quay.io/djodha/test-gitopscon:ok-stage
        ports:
        - containerPort: 80
