# base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: staging-service
spec:
  ports:
    - name: staging-http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
