apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-application
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: https://github.com/dheerajodha/prep
    path: overlays/production
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: production-ns

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
