# overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
- path: dep-patch.yaml
  target:
    kind: Deployment
    name: my-deployment

images:
  - name: quay.io/djodha/test-gitopscon
    newTag: ok-prod
