# overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
- path: dep-patch.yaml
  target:
    kind: Deployment
    name: my-deployment
- path: service-patch.yaml
  target:
    kind: Service
    name: my-service
