apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/dheerajodha/prep
    path: base
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: base-ns

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
