# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app

