# base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: base-service
spec:
  selector:
    app: example-app
  ports:
    - name: base-http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
